### ISSUE TITLE
[Feat]: 댓글 API 기능 구현

### ISSUE THREAD

**Issue by kkang0** [Team-DevHub/dev-hub-back#5]
## 기능 개요
> 댓글(comments) API 구현

## 작업 상세 내용
- [x] 댓글 작성 API : writeComment
- [x] 댓글 삭제 API : deleteComment
- [x] 댓글 query 파일 추가 : commentQuery.js

**Comment by kkang0** [comment]
댓글 조회 모듈 추가해서 푸시했습니다! 지민님이 하신 것처럼 utils에 getComments.js 파일을 하나 추가했는데 이렇게 하는 게 맞을까요?

**Comment by JIMIN1020** [comment]
> 댓글 조회 모듈 추가해서 푸시했습니다! 지민님이 하신 것처럼 utils에 getComments.js 파일을 하나 추가했는데 이렇게 하는 게 맞을까요?

네!! 기존 브랜치에서 추가하신거면 pr 다시 열어주세요!
